task_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tm_app.urls')),
    path('', include('users.urls')),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tm_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),

    path('departments/', views.DepartmentList.as_view(), name='department_view'),
    path('department/create', views.DepartmentCreate.as_view(), name='department_create'),
    path('department/<int:pk>/update', views.DepartmentUpdate.as_view(), name='department_update'),
    path('department/<int:pk>/delete', views.DepartmentDelete.as_view(), name='department_delete'),

    path('staff/', views.staff, name='staff'),

    path('tasks/', views.TaskList.as_view(), name='task_view'),
    path('task/create', views.TaskCreate.as_view(), name='task_create'),
    path('task/<int:pk>/update', views.TaskUpdate.as_view(), name='task_update'),
    path('task/<int:pk>/delete', views.TaskDelete.as_view(), name='task_delete'),
    path('task/<int:pk>', views.task_detail, name='task_detail'),
    path('task/<int:pk>/assign', views.assign_task, name='assign_task'),
    path('task/<int:pk>/unassign', views.unassign_task, name='unassign_task'),
    path('task/<int:pk>/complete', views.markAsCompleted, name='markAsCompleted'),

]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('profile/<int:pk>/update', views.profile_update, name='profile_update'),

    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
]

tm_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('department_view')

class Task(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    managed_by = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    assigned_to = models.ManyToManyField(User, related_name='assigned_tasks')
    due_date = models.DateField(default=timezone.now() + timezone.timedelta(days=1))
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('task_detail', args=[str(self.id)])

tm_app/forms.py
from django import forms
from .models import User, Department, Task
from django.contrib.auth.forms import UserCreationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit

class DepartmentCreateForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = '__all__'

class DepartmentUpdateForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = '__all__'

class TaskCreateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'department', 'managed_by', 'due_date']
    
    def __init__(self, *args, **kwargs):
        super(TaskCreateForm, self).__init__(*args, **kwargs)
        self.fields['managed_by'].queryset = User.objects.filter(userprofile__is_manager=True)

class TaskUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'department', 'managed_by', 'due_date', 'is_completed']

tm_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from . import models
from . import forms
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import logout, authenticate, login


# Create your views here.
def home(request):
    department_list = models.Department.objects.all()
    return render(request, 'tm_app/home.html', {'department_list': department_list})

class DepartmentCreate(CreateView):
    model = models.Department
    form_class = forms.DepartmentCreateForm
    template_name = 'tm_app/department_create.html'

class DepartmentList(ListView):
    model = models.Department
    template_name = 'tm_app/department_view.html'

class DepartmentUpdate(UpdateView):
    model = models.Department
    form_class = forms.DepartmentUpdateForm
    template_name = 'tm_app/department_update.html'

class DepartmentDelete(DeleteView):
    model = models.Department
    success_url = '/departments/'
    template_name = 'tm_app/department_delete.html'

def staff(request):
    users = User.objects.all()
    departments = models.Department.objects.all()
    return render(request, 'tm_app/staff.html', {'users': users, 'departments': departments})

class TaskList(LoginRequiredMixin, ListView):
    model = models.Task
    template_name = 'tm_app/task_view.html'

class TaskCreate(LoginRequiredMixin, CreateView):
    model = models.Task
    form_class = forms.TaskCreateForm
    template_name = 'tm_app/task_create.html'

class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = models.Task
    form_class = forms.TaskUpdateForm
    template_name = 'tm_app/task_update.html'

class TaskDelete(LoginRequiredMixin, DeleteView):
    model = models.Task
    success_url = '/tasks/'
    template_name = 'tm_app/task_delete.html'


@login_required
def task_detail(request, pk):
    task = get_object_or_404(models.Task, pk=pk)
    return render(request, 'tm_app/task_detail.html', {'task': task})

@login_required
def assign_task(request, pk):
    task = get_object_or_404(models.Task, pk=pk)
    task.assigned_to.add(request.user)
    task.save()
    return redirect('task_detail', pk=pk)

@login_required
def unassign_task(request, pk):
    task = get_object_or_404(models.Task, pk=pk)
    task.assigned_to.remove(request.user)
    task.save()
    return redirect('task_detail', pk=pk)

@login_required
def markAsCompleted(request, pk):
    if request.method == 'POST':
        task = get_object_or_404(models.Task, pk=pk)
        task.is_completed = True
        task.save()
        return redirect('task_detail', pk=pk)
    task = get_object_or_404(models.Task, pk=pk)
    return render(request, 'tm_app/task_complete.html', {'task': task})

tm_app/templates/tm_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% load static %}
    <link rel="icon" href="{% static 'tm_app/icon/favicon.ico' %}">

    <link rel="stylesheet" href="{% static 'tm_app/style.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    {% block head %}
        
    {% endblock %}
</head>
<body>
    <div class="header">
        <h1>pineApple Task Manager</h1>
    </div>
    <nav>
        <div class="toggle_btn">
            <p class="menu_text">Open menu <i class="fa-solid fa-bars"></i></p>
        </div>
        <div class="dropdown_menu">
            {% if user.is_authenticated %}
                <div class="profile_header" id="profile" data-url="{% url 'profile' %}" onclick="openProfile()">
                    <img src="{{ user.userprofile.image.url }}" alt="{{ user.username }}"   width="50px"height="auto">
                    <p>{{ user.first_name }} {{ user.last_name }}</p>
                </div>
            {% endif %}
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'department_view' %}">Departments</a></li>
            <li><a href="{% url 'staff' %}">Staff</a></li>
            <li><a href="{% url 'task_view' %}">Tasks</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'register' %}">Register</a></li>
            {% endif %}
        </div>
    </nav>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <footer>
        <p>&copy; 2023 pineApple Task Manager. All rights reserved.</p>
    </footer>

    <script src="{% static 'tm_app/script.js' %}"></script>

    <script src="https://kit.fontawesome.com/62b05945c2.js" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

tm_app/templates/tm_app/department_create.html
{% extends 'tm_app/base.html' %}

{% load crispy_forms_tags %}

{% block head %}
    <title>Create Department</title>
{% endblock %}

{% block content %}
    <legend class="border-bottom mb-4">Department Create</legend>
    <br>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-primary">Create</button>
    </form>
{% endblock %}

tm_app/templates/tm_app/department_delete.html
{% extends 'tm_app/base.html' %}
{% block content %}
    <h2>Department Delete</h2>
    <form method="POST">
        {% csrf_token %}
        <h4 class="form_alert">Are you sure you want to delete "{{ object.name }}" department?</h4>
        <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
    </form>
{% endblock %}

tm_app/templates/tm_app/department_update.html
{% extends 'tm_app/base.html'%}

{% load crispy_forms_tags %}

{% block head %}
    <title>Update - {{ object.name }}</title>
{% endblock %}

{% block content %}
    <h2>Department Update</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-primary">Update</button>
    </form>
{% endblock %}

tm_app/templates/tm_app/department_view.html
{% extends 'tm_app/base.html' %}

{% load static %}

{% block head %}
    <title>Departments</title>
{% endblock %}

{% block content %}
<legend class="border-bottom mb-4">Our Departments</legend>
    <br>
    {% if user.is_superuser %}
        <a href="{% url 'department_create' %}">Create Department</a>
    {% endif %}
    <table>
        <tr>
            <th>Nr</th>
            <th>Name</th>
            {% if user.is_superuser %}
                <th class="td_center">Update</th>
                <th class="td_center">Delete</th>
            {% endif %}
        </tr>
        {% for department in department_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ department.name }}</td>
                {% if user.is_superuser %}
                    <td class="td_center"><a href="{% url 'department_update' department.id %}"><i class="fa-solid fa-pencil table_update"></i></td>
                    <td class="td_center"><a href="{% url 'department_delete' department.id %}"><i class="fa-solid fa-xmark table_delete"></i></td>
                {% endif %}
            </tr>
        {% endfor %}
        </tr>
    </table>
{% endblock %}

tm_app/templates/tm_app/home.html
{% extends 'tm_app/base.html' %}

{% block head %}
    <title>Home</title>
{% endblock %}

{% block content %}
<legend class="border-bottom mb-4">Home</legend>
<p>Welcome to PineApple Task Manager – Your Essential Tool for Simplified Task Management!</p>

<p>At PineApple, we understand the demands of modern work environments, and we're here to make your task management experience seamless and effective. Our Task Manager is designed with simplicity and productivity in mind, ensuring you can effortlessly organize, prioritize, and collaborate on tasks without unnecessary complications.</p>
    
<p><strong>Key Features:</strong></p>

<ol>
    <li><strong>Intuitive Interface:</strong> Enjoy a clean and user-friendly design, making it easy for you to navigate and manage your tasks efficiently.</li>
    <li><strong>Task Organization:</strong> Create, edit, and categorize tasks effortlessly, allowing you to stay organized and focused on what matters most.</li>
    <li><strong>Deadline Tracking:</strong> Never miss a deadline again! Set due dates for your tasks and receive timely reminders to keep you on track.</li>
    <li><strong>Team Collaboration:</strong> Enhance teamwork with shared projects and easy communication, fostering collaboration across your organization.</li>
</ol>

<p><strong>Why Use PineApple Task Manager?</strong></p>

<ul>
    <li><strong>Simplicity at its Core:</strong> We believe in keeping things simple. PineApple Task Manager provides the essential features you need without overwhelming complexity.</li>
    <li><strong>Accessibility Anytime, Anywhere:</strong> Whether you're in the office or on the go, access your tasks from any device with our responsive and mobile-friendly design.</li>
    <li><strong>Reliable Performance:</strong>PineApple Task Manager is built for stability and reliability, ensuring a consistent experience for all users.</li>
</ul>

<p>While we may not have progress monitoring and file integration at the moment, we are constantly evolving to meet the needs of our users. Your feedback is crucial in shaping the future of PineApple Task Manager.</p>
    
<p>Start your journey towards efficient task management with PineApple today. Your success begins with organized tasks!</p>
{% endblock %}

tm_app/templates/tm_app/staff.html
{% extends 'tm_app/base.html' %}

{% block head %}
    <title>Staff</title>
{% endblock %}

{% block content %}
<legend class="border-bottom mb-4">Meet our team</legend>

{% for department in departments %}
    <legend class="border-bottom mb-4" id="department_name">{{ department.name }} department</legend>
    <div class="grid_list">
        {% for user in users %}
            {% if user.userprofile.department == department %}
                <div class="card" style="width: 18rem;">
                    <img src="{{ user.userprofile.image.url }}" class="card-img-top" id="card_photo" alt="  {{    user.username }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ user.first_name }} {{ user.last_name }}</h5>
                        <p class="card-text"><strong>Department:</strong> {{ user.userprofile.department }}</p>
                        <p class="card-text"><strong>Email:</strong> {{ user.email }}</p>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endfor %}
{% endblock %}

tm_app/templates/tm_app/task_complete.html
{% extends 'tm_app/base.html' %}

{% block head %}
    <title>Complete - {{ task.name }}</title>
{% endblock %}

{% block content %}
    <h2>Complete task: {{ task.name }}</h2>
    <form action="{% url 'markAsCompleted' task.id %}" method="POST">
        {% csrf_token %}
        <h4 class="form_alert">Are you sure you want to mark "{{ task.name }}" task as completed?</h4>
        <button type="submit" class="btn btn-outline-success btn-sm">Mark as completed</button>
        <input type="button" class="btn btn-outline-danger btn-sm" value="Cancel" onclick="window.history.back()">
    </form>
{% endblock %}

tm_app/templates/tm_app/task_create.html
{% extends 'tm_app/base.html' %}

{% load crispy_forms_tags %}

{% block head %}
    <title>Create Task</title>
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create Task</legend>
            {{ form|crispy }}
        </fieldset>
        <button type="submit" class="btn btn-outline-primary">Create</button>
    </form>
{% endblock %}

tm_app/templates/tm_app/task_delete.html
{% extends 'tm_app/base.html' %}

{% block head %}
    <title>Delete - {{ task.name }}</title>
{% endblock %}

{% block content %}
    <h2>Delete Task</h2>
    <form method="POST">
        {% csrf_token %}
        <h4 class="form_alert">Are you sure you want to delete "{{ task.name }}" task?</h4>
        <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
        <input type="button" class="btn btn-outline-danger btn-sm" value="Cancel" onclick="window.history.back()">
    </form>
{% endblock %}

tm_app/templates/tm_app/task_detail.html
{% extends 'tm_app/base.html' %}

{% block head %}
    <title>{{ task.name }}</title>
{% endblock %}

{% block content %}
    <legend class="border-bottom mb-4">Task Details</legend>
    <h3>{{ task.name }}</h3>
    {% if not task.is_completed %}
        {% if user.is_superuser or user.userprofile.is_manager %}
            <a href="{% url 'task_update' task.id %}">Update</a>
            <a href="{% url 'task_delete' task.id %}">Delete</a>
        {% endif %}
    {% endif %}
    <p class="task_muted"><strong>Department:</strong> {{ task.department }}</p>
    <p class="task_muted"><strong>Managed by:</strong> {{ task.managed_by.first_name }} {{ task.managed_by.last_name }}</p>
    <br>
    <h4>Todo:</h4>
    <p>{{ task.description }}</p>
    {% if not task.is_completed %}
        {% if request.user != task.managed_by %}
            {% if user in task.assigned_to.all %}
                <form action="{% url 'unassign_task' task.id %}" method="post">
                {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger btn-sm">Unassign task</button>
                </form>
            {% else %}
                <form action="{% url 'assign_task' task.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-info btn-sm">Assign to me</button>
                </form>
            {% endif %}
        {% endif %}
    {% endif %}
    {% if not task.is_completed %}
        {% if request.user == task.managed_by or user in task.assigned_to.all or user.is_superuser %}
            <form action="{% url 'markAsCompleted' task.id %}" method="GET">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-success btn-sm">Mark as completed</button>
            </form>
        {% endif %}
    {% endif %}
    <br>
    <hr>
    {% if task.assigned_to.all %}
        {% if task.is_completed %}
            <h3>Completed by:</h3>
        {% else %}
            <h3>Currently working on the task:</h3>
        {% endif %}
        <div class="grid_list">
            {% for worker in task.assigned_to.all %}
                <div class="card mb-3" style="max-width: 25em">
                    <div class="row g-0">
                        <div class="col-md-4" style="display: flex; justify-content: center; align-items: center;">
                            <img src="{{ worker.userprofile.image.url }}" class="img-fluid rounded-start" alt="{{ worker.first_name }} {{ worker.last_name }}" id="worker_photo">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ worker.first_name }} {{ worker.last_name }}</h5>
                                <p class="card-text"><strong>Email:</strong> {{ worker.email }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>Oops! No one took this task.</h3>
    {% endif %}
{% endblock %}

tm_app/templates/tm_app/task_update.html
{% extends 'tm_app/base.html' %}

{% load crispy_forms_tags %}

{% block head %}
    <title>Update - {{ task.name }}</title>
{% endblock %}

{% block content %}
    <h2>Task Update</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-primary">Update</button>
    </form>
{% endblock %}

tm_app/templates/tm_app/task_view.html
{% extends 'tm_app/base.html' %}

{% block head %}
    <title>Tasks</title>
{% endblock %}

{% block content %}
    <legend class="border-bottom mb-4">Open tasks</legend>
    {% if user.is_superuser or user.userprofile.is_manager %}
        <a href="{% url 'task_create' %}">Create Task</a>
    {% endif %}
    {% if task_list %}
        <div class="grid_list">
            {% for task in task_list %}
                {% if not task.is_completed %}
                    <div class="card" style="width: 18rem;">
                        <div class="card-body" id="task_card" data-url-task="{% url 'task_detail' task.id %}"           onclick="openTask(event)">
                            <h5 class="card-title">{{ task.name }}</h5>
                            <h6 class="card-subtitle mb-2 text-body-secondary">{{ task.managed_by}}</h6>
                            <p class="card-text">{{ task.description }}</p>
                            {% if request.user == task.managed_by or user.is_superuser %}
                                <a href="{% url 'task_delete' task.id %}" class="card-link">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <br>
        <legend class="border-bottom mb-4">Completed tasks</legend>
        <div class="grid_list">
            {% for task in task_list %}
                {% if task.is_completed %}
                    <div class="card" style="width: 18rem;">
                        <div class="card-body" id="task_card" data-url-task="{% url 'task_detail' task.id %}"           onclick="openTask(event)">
                            <h5 class="card-title">{{ task.name }}</h5>
                            <h6 class="card-subtitle mb-2 text-body-secondary">{{ task.managed_by}}</h6>
                            <p class="card-text">{{ task.description }}</p>
                            {% if request.user == task.managed_by or user.is_superuser %}
                                <a href="{% url 'task_delete' task.id %}" class="card-link">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    {% else %}
        <p>Seems you haven't created any tasks yet. Thus you can enjoy your free time, since you have nothing to do :)</p>
    {% endif %}
{% endblock %}